// <auto-generated />
using System;
using KYC_AzaKaw_Core.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KYC_AzaKaw_Core.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20191102111838_SecondTime")]
    partial class SecondTime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KYC_AzaKaw_Core.Model.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("KYC_AzaKaw_Core.Model.MrzInfo", b =>
                {
                    b.Property<int>("MrzId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalInfo");

                    b.Property<string>("BirthDate");

                    b.Property<string>("BirthDateCheck");

                    b.Property<string>("BirthDateVerified");

                    b.Property<string>("Checksum");

                    b.Property<string>("ChecksumVerified");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("CustomerId");

                    b.Property<string>("DocumentNumber");

                    b.Property<string>("DocumentNumberCheck");

                    b.Property<string>("DocumentNumberVerified");

                    b.Property<string>("DocumentSubtype");

                    b.Property<string>("DocumentType");

                    b.Property<string>("ExpiryDate");

                    b.Property<string>("ExpiryDateCheck");

                    b.Property<string>("ExpiryDateVerified");

                    b.Property<string>("FileName");

                    b.Property<string>("FileNameUnique");

                    b.Property<string>("IssuingCountry");

                    b.Property<string>("Line1");

                    b.Property<string>("Line2");

                    b.Property<string>("MrzType");

                    b.Property<string>("Nationality");

                    b.Property<string>("Sex");

                    b.Property<bool>("isKYCVerified");

                    b.HasKey("MrzId");

                    b.HasIndex("CustomerId");

                    b.ToTable("MrzInfos");
                });

            modelBuilder.Entity("KYC_AzaKaw_Core.Model.MrzInfo", b =>
                {
                    b.HasOne("KYC_AzaKaw_Core.Model.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
